# Generated by Django 6.0.2 on 2026-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Electronics', 'Electronics'), ('Beauty', 'Beauty'), ('Grocery', 'Grocery')], default='Fashion', max_length=100),
        ),
    ]
