# Generated by Django 6.0.2 on 2026-05-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Electronics', 'Electronics'), ('Beauty', 'Beauty'), ('Appliances', 'Appliances')], default='Fashion', max_length=100),
        ),
    ]
