# Generated by Django 6.0.2 on 2026-06-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_image2_product_image3_product_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Online Payment', 'Online Payment'), ('Cash on Delivery', 'Cash on Delivery')], default='Online Payment', max_length=50),
        ),
    ]
